-- please don't eat these medicines without doctor prescription.
USE lilavati;
CREATE TABLE subscription (
    subscription_id INT AUTO_INCREMENT PRIMARY KEY,
    medicine_name VARCHAR(100),
    report TEXT,
    bill_id INT,
    docter_id INT,
    FOREIGN KEY (bill_id) REFERENCES billing_counter(bill_id),
    FOREIGN KEY (docter_id) REFERENCES docter(docter_id)
);

INSERT INTO subscription (medicine_name, report, bill_id, docter_id) VALUES
('Paracetamol', 'No major issue found.', 5, 21),
('Cetirizine', 'Recommended for blood test.', 37, 44),
('Metformin', 'MRI suggested for confirmation.', 29, 22),
('Amlodipine', 'Signs of infection detected.', 3, 26),
('Cetirizine', 'MRI suggested for confirmation.', 42, 2),
('Pantoprazole', 'Recommended for blood test.', 49, 27),
('Dolo 650', 'No major issue found.', 36, 33),
('Pantoprazole', 'Recommended for blood test.', 8, 6),
('Ibuprofen', 'Signs of infection detected.', 35, 43),
('Amoxicillin', 'Vitals stable.', 15, 6),
('Amoxicillin', 'Vitals stable.', 43, 17),
('Dolo 650', 'No major issue found.', 27, 15),
('Paracetamol', 'Patient recovering well.', 26, 1),
('Atorvastatin', 'Vitals stable.', 41, 43),
('Amoxicillin', 'Vitals stable.', 11, 2),
('Atorvastatin', 'Patient recovering well.', 8, 46),
('Amlodipine', 'No major issue found.', 1, 5),
('Cetirizine', 'MRI suggested for confirmation.', 12, 26),
('Amlodipine', 'Signs of infection detected.', 1, 10),
('Metformin', 'Signs of infection detected.', 24, 22),
('Ibuprofen', 'Recommended for blood test.', 19, 45),
('Amlodipine', 'Recommended for blood test.', 9, 14),
('Azithromycin', 'Patient recovering well.', 14, 33),
('Dolo 650', 'Follow-up required after 1 week.', 39, 23),
('Ibuprofen', 'Follow-up required after 1 week.', 16, 50),
('Ibuprofen', 'No major issue found.', 40, 41),
('Dolo 650', 'Vitals stable.', 15, 7),
('Pantoprazole', 'Prescribed medication for 5 days.', 24, 16),
('Dolo 650', 'Referred to specialist.', 20, 18),
('Atorvastatin', 'Prescribed medication for 5 days.', 49, 15),
('Atorvastatin', 'Needs further observation.', 26, 35),
('Amoxicillin', 'Needs further observation.', 18, 11),
('Dolo 650', 'No major issue found.', 3, 29),
('Paracetamol', 'No major issue found.', 33, 30),
('Amoxicillin', 'Needs further observation.', 40, 34),
('Amoxicillin', 'MRI suggested for confirmation.', 31, 7),
('Amlodipine', 'Follow-up required after 1 week.', 2, 31),
('Dolo 650', 'Recommended for blood test.', 19, 5),
('Amoxicillin', 'Patient recovering well.', 31, 35),
('Atorvastatin', 'Prescribed medication for 5 days.', 28, 17),
('Pantoprazole', 'Prescribed medication for 5 days.', 41, 31),
('Azithromycin', 'Prescribed medication for 5 days.', 49, 47),
('Azithromycin', 'Signs of infection detected.', 37, 37),
('Paracetamol', 'MRI suggested for confirmation.', 3, 48),
('Paracetamol', 'Patient recovering well.', 50, 43),
('Metformin', 'Patient recovering well.', 39, 4),
('Atorvastatin', 'Referred to specialist.', 43, 36),
('Metformin', 'Signs of infection detected.', 27, 49),
('Pantoprazole', 'Signs of infection detected.', 49, 41),
('Amlodipine', 'Patient recovering well.', 17, 42);
